{% set name = "comtypes" %}
{% set version = "1.1.12" %}
{% set sha256 = "d3976d5610ca87299ac6a9595e412e12d14806d77dc12cd7c9bf72206256cf34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/enthought/comtypes/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [not win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - comtypes

about:
  home: http://starship.python.net/crew/theller/comtypes/
  license: MIT
  license_file: LICENSE.txt
  summary: pure Python COM package
  description: |
    comtypes is a pure Python COM package based on the ctypes ffi foreign
    function library.The comtypes package makes it easy to access and implement
    both custom and dispatch based COM interfaces.While the pywin32 package
    contains superior client side support for dispatch based COM interfaces,it is
    not possible to access custom COM interfaces unless they are wrapped in
    C++-code.
  doc_url: http://pythonhosted.org/comtypes/
  doc_source_url: https://github.com/enthought/comtypes/blob/master/docs/source/index.rst
  dev_url: https://github.com/enthought/comtypes/

extra:
  recipe-maintainers:
    - nehaljwani
